# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and is able to run tests across different versions of node. This workflow is based on Github Actions Node.js starter workflow (https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml, for more information about Github Actions Node.js starter workflow see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs)

name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # Feel free to change or add versions, e.g. node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
